{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctfd.nginx.fullname" . }}
  labels:
    {{- include "ctfd.nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ctfd.nginx.selectorLabels" . | nindent 4 }}
{{- end }}
