apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ include "ctfd.secretKey" . | quote }}
  database-url: {{ include "ctfd.databaseUrl" . | quote }}
  redis-url: {{ include "ctfd.redisUrl" . | quote }}
{{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | quote }}
{{- end }}
